#!/bin/sh

set -e -u


error()
{
    case $1 in
        "
"*) ;;
        *) printf '\n' >&2
    esac

    printf '%s' "$1" >&2

    case $1 in
        *"
") ;;
        *) printf '\n' >&2
    esac
    exit 1
}


command -v ffmpeg >/dev/null || error "ffmpeg not found in \$PATH!"


badargs()
{
	bin="./$(basename "$0")"
	syntax="
Syntax:

    $bin [options] <profile> <input_file> <output_file>

    $bin [options] <profile> <input_file> ... <output_directory>

The container format is guessed by the file extension of the output file.
E.g. \".mp4\" generates an MPEG 4 container file, whereas \".webm\" would
generate a WEBM container, and \".mov\" would create a MOV container.

If output is a directory, the same file name as input will be used, except for
the file extension which will be the default extension for the default
container format of the chosen profile, unless overridden by the \"extension\"
option.

NOTE:
Not all codecs can be used in all container formats!

Options:

    NOTE:
    Options can be shortened. E.g. \"vol\" and \"volume\" are the same option.

    sc[ale]=half|quarter|double|x%|w:h

        half    - Halves the video resolution.
        quarter - Quarters the video resolution.
        double  - Doubles the video resolution.
        x%      - Scales the video by x percent (up or down).
        w:h     - Scales to width (w) and height (h).
                  Set either one to -1 and it will be calculated by the other
                  value to maintain the video aspect ratio.


    vol[ume]=<p%|max>

        Volume can either be in percent (\"90%\"), allowing increasing and
        decreasing volume by any amount desired (up to the point where the
        output clips), or it can be \"max\" in which case the maximum
        amplication is calculated that is possible without causing any
        clipping.


    ext[ension]=<ext>

        Overrides output file extension in case output is a directory,
        e.g. \"ext=mp3\". Has no effect if output is a file name.


Valid profile names are:

    vlow  - Very low quality (H.264/AAC).
    low   - Low quality (H.264/AAC).
    std   - Standard quality (H.264/AAC).
    high  - High quality (H.264/AAC).
    vhigh - Very high quality (H.264/AAC).

	500k - Limit total bandwidth to 500kbit/s (H.264/AAC).
	1m   - Limit total bandwidth to 1Mbit/s (H.264/AAC).
	2m   - Limit total bandwidth to 2Mbit/s (H.264/AAC).
	3m   - Limit total bandwidth to 3Mbit/s (H.264/AAC).
	4m   - Limit total bandwidth to 4Mbit/s (H.264/AAC).
	6m   - Limit total bandwidth to 6Mbit/s (H.264/AAC).
	8m   - Limit total bandwidth to 8Mbit/s (H.264/AAC).

    scrcast - Screencast with very low bitrate (H.264/AAC).
    webcast - Web screencast with low bitrate (VP9/Opus).

    bug     - Screen recording for bug reporting (H.264).
	bugwebm - As bug but using VP9 (VP9).

    gif  - Animated GIF (or APNG).
    gifo - Animated GIF (or APNG) w/ optimized palette.

    transform - Copy audio/video data unmodified, just rewrite container.
"
	error "$syntax"
}


scale=
volume=
outfileExt=

profile=

output=
inCount=0


while [ -z "$output" ]
do
    if [ $# -lt 3 ]
    then
        printf "%s\n" "Too little arguments!" >&2
        badargs
    fi

    case $1 in

		"sc="*)
			scale=${1#"sc="}
			shift
		;;
		"scale="*)
			scale=${1#"scale="}
			shift
		;;

        "vol="*)
            volume=${1#"vol="}
            shift
        ;;
        "volume="*)
            volume=${1#"volume="}
            shift
        ;;

        "ext="*)
            outfileExt=${1#"ext="}
            shift
        ;;
        "extension="*)
            outfileExt=${1#"extension="}
            shift
        ;;

        *)
            profile=$1
            shift
            inCount=$(( $# - 1 ))
            eval "output=\${$#}"
        ;;
    esac
done

if [ $inCount -gt 1 ] && [ ! -d "$output" ]
then
    error "Multiple input files are only allowed if output is a directory!"
fi

volarg=
case "$volume" in

    "")
        # No volume set - fine
    ;;

    "max")
        # We'll take care of that later
        volume="max"
    ;;

    *"%")
        volarg=${volume%"%"}
        volarg="volume=$volarg/100"
    ;;

    *)
        error "Bad volume value \"$volume\"!"
    ;;
esac


scarg=
case "$scale" in

	"")
		# No scale set
	;;

	*":"*)
		scarg="scale=$scale"
		# Width and height set
	;;

	"half")
		scarg="scale=0.5*iw:-1"
	;;

	"quarter")
		scarg="scale=0.25*iw:-1"
	;;

	"double")
		scarg="scale=2*iw:-1"
	;;

	*"%")
		scarg=${scale%"%"}
		scarg="scale=$scarg/100*iw:-1"
	;;

	*)
		error "Bad scale value \"$scale\"!"
	;;
esac

[ -z "$scarg" ] || \
	scarg="$scarg:force_original_aspect_ratio=decrease:force_divisible_by=8"


onexit()
{
	oldtraps=$(trap)
	oldexit=$(echo "$oldtraps" \
		| grep "EXIT$" \
		| sed -E 's/^trap -- (.*) EXIT$/\1/')
	if [ -n "$oldexit" ]
	then
		# shellcheck disable=SC2064
		trap "eval $oldexit ; $1" EXIT
	else
		# shellcheck disable=SC2064
		trap "$1" EXIT
	fi
}


encargs=""
decargs=""
twopass=""


hascoder()
{
	encfound=$(ffmpeg -encoders 2>/dev/null | grep -E "^ [^ ]+ $1 ")
	if [ -n "$encfound" ]
	then
		return 0
	fi
	return 1
}


#  $1  - bitrate in kbit/s (must be 16 kbit/s or higher)
# ($2) - "stereo" or "mono"; default is "stereo"
# ($3) - force HE/HEv2: "yes" or "no"; default is "no"
activate_aac()
{
	if [ "$1" -lt 16 ]
	then
		echo "AAC bitrate too low!" >&2
		exit 1
	fi

	if [ "${2:-"stereo"}" = "mono" ]
	then
		encargs="$encargs -ac 1" # Convert audio to mono
	else
		encargs="$encargs -ac 2" # Convert audio to stereo
	fi

	encargs="$encargs -b:a ${1}k" # Set bitrate in kbit/s

	if [ "$1" -lt 80 ] || [ "${3:-"no"}" = "yes" ]
	then
		if [ "${2:-"stereo"}" = "mono" ]
		then
			if hascoder "aac_at"
			then
				encargs="$encargs -c:a aac_at" # AAC audio
				encargs="$encargs -profile:a 28" # Use HEv2 encoding
				return
			fi

			if hascoder "libfdk_aac"
			then
				encargs="$encargs -c:a libfdk_aac" # AAC audio
				encargs="$encargs -profile:a aac_he_v2" # Use HEv2 encoding
				return
			fi
		fi

		if hascoder "aac_at"
		then
			encargs="$encargs -c:a aac_at" # AAC audio
			encargs="$encargs -profile:a 4" # Use HE encoding
			return
		fi

		if hascoder "libfdk_aac"
		then
			encargs="$encargs -c:a libfdk_aac" # AAC audio
			encargs="$encargs -profile:a aac_he" # Use HE encoding
			return
		fi

		if [ "${3:-"no"}" = "yes" ]
		then
			echo "No encoder with HE/HEv2 support found!" >&2
			exit 1
		fi

		# Fallback to non HE/HEv2 if allowed
		if hascoder "aac"
		then
			encargs="$encargs -c:a aac" # AAC audio
			encargs="$encargs -aac_coder twoloop" # Tread CPU time for quality
			return
		fi
	fi

	if hascoder "aac_at"
	then
		encargs="$encargs -c:a aac_at" # AAC audio
		encargs="$encargs -aac_at_mode abr" # Set ABR mode
		return
	fi

	if hascoder "libfdk_aac"
	then
		encargs="$encargs -c:a libfdk_aac" # AAC audio
		return
	fi

	if hascoder "aac"
	then
		encargs="$encargs -c:a aac" # AAC audio
		encargs="$encargs -aac_coder twoloop" # Tread CPU time for quality
		return
	fi

	echo "No AAC encoder found!" >&2
	exit 1
}


case "$profile" in

	"vlow")
		# Video
		encargs="$encargs -c:v h264" # H.264 video
		encargs="$encargs -pix_fmt yuv420p" # Keep H.264 high profile valid
		encargs="$encargs -vsync vfr" # Allow varible frame rate
		encargs="$encargs -crf 34" # Encode all frames with same quality
		encargs="$encargs -profile:v high" # Use H.264 high profile
		encargs="$encargs -level:v 5.2" # Use level 5.2
		encargs="$encargs -preset veryslow" # Treat time for compression
		# Audio
		activate_aac 96
		# Other
		[ -z "$outfileExt" ] && outfileExt="mp4"
	;;

	"low")
		# Video
		encargs="$encargs -c:v h264" # H.264 video
		encargs="$encargs -pix_fmt yuv420p" # Keep H.264 high profile valid
		encargs="$encargs -vsync vfr" # Allow varible frame rate
		encargs="$encargs -crf 28" # Encode all frames with same quality
		encargs="$encargs -profile:v high" # Use H.264 high profile
		encargs="$encargs -level:v 5.2" # Use level 5.2
		encargs="$encargs -preset slower" # Treat time for compression
		# Audio
		activate_aac 128
		# Other
		[ -z "$outfileExt" ] && outfileExt="mp4"
	;;

	"std")
		# Video
		encargs="$encargs -c:v h264" # H.264 video
		encargs="$encargs -pix_fmt yuv420p" # Keep H.264 high profile valid
		encargs="$encargs -vsync vfr" # Allow varible frame rate
		encargs="$encargs -crf 24" # Encode all frames with same quality
		encargs="$encargs -profile:v high" # Use H.264 high profile
		encargs="$encargs -level:v 5.2" # Use level 5.2
		encargs="$encargs -preset slow" # Treat time for compression
		# Audio
		activate_aac 144
		# Other
		[ -z "$outfileExt" ] && outfileExt="mp4"
	;;


	"high")
		# Video
		encargs="$encargs -c:v h264" # H.264 video
		encargs="$encargs -pix_fmt yuv420p" # Keep H.264 high profile valid
		encargs="$encargs -vsync vfr" # Allow varible frame rate
		encargs="$encargs -crf 21" # Encode all frames with same quality
		encargs="$encargs -profile:v high" # Use H.264 high profile
		encargs="$encargs -level:v 5.2" # Use level 5.2
		encargs="$encargs -preset slower" # Treat time for compression
		# Audio
		activate_aac 160
		# Other
		[ -z "$outfileExt" ] && outfileExt="mp4"
	;;

	"vhigh")
		# Video
		encargs="$encargs -c:v h264" # H.264 video
		encargs="$encargs -pix_fmt yuv420p" # Keep H.264 high profile valid
		encargs="$encargs -vsync vfr" # Allow varible frame rate
		encargs="$encargs -crf 18" # Encode all frames with same quality
		encargs="$encargs -profile:v high" # Use H.264 high profile
		encargs="$encargs -level:v 5.2" # Use level 5.2
		encargs="$encargs -preset veryslow" # Treat time for compression
		# Audio
		activate_aac 192
		# Other
		[ -z "$outfileExt" ] && outfileExt="mp4"
	;;


	"500k")
		# Video
		encargs="$encargs -maxrate 500k" # Set max total bitrate
		encargs="$encargs -bufsize 3M" # Set buffer size
		encargs="$encargs -c:v h264" # H.264 video
		encargs="$encargs -pix_fmt yuv420p" # Keep H.264 high profile valid
		encargs="$encargs -vsync vfr" # Allow varible frame rate
		encargs="$encargs -b:v 436k" # Set video bitrate
		encargs="$encargs -profile:v high" # Use H.264 high profile
		encargs="$encargs -level:v 5.2" # Use level 5.2
		encargs="$encargs -preset veryslow" # Treat more time for quality
		# Audio
		activate_aac 64
		# Other
		twopass=1
		[ -z "$outfileExt" ] && outfileExt="mp4"
	;;

	"1m")
		# Video
		encargs="$encargs -maxrate 1M" # Set max total bitrate
		encargs="$encargs -bufsize 2M" # Set buffer size
		encargs="$encargs -c:v h264" # H.264 video
		encargs="$encargs -pix_fmt yuv420p" # Keep H.264 high profile valid
		encargs="$encargs -vsync vfr" # Allow varible frame rate
		encargs="$encargs -b:v 904k" # Set video bitrate
		encargs="$encargs -profile:v high" # Use H.264 high profile
		encargs="$encargs -level:v 5.2" # Use level 5.2
		encargs="$encargs -preset veryslow" # Treat more time for quality
		# Audio
		activate_aac 96
		# Other
		twopass=1
		[ -z "$outfileExt" ] && outfileExt="mp4"
	;;

	"2m")
		# Video
		encargs="$encargs -maxrate 2M" # Set max total bitrate
		encargs="$encargs -bufsize 2M" # Set buffer size
		encargs="$encargs -c:v h264" # H.264 video
		encargs="$encargs -pix_fmt yuv420p" # Keep H.264 high profile valid
		encargs="$encargs -vsync vfr" # Allow varible frame rate
		encargs="$encargs -b:v 1872k" # Set video bitrate
		encargs="$encargs -profile:v high" # Use H.264 high profile
		encargs="$encargs -level:v 5.2" # Use level 5.2
		encargs="$encargs -preset slower" # Treat more time for quality
		# Audio
		activate_aac 128
		# Other
		twopass=1
		[ -z "$outfileExt" ] && outfileExt="mp4"
	;;

	"3m")
		# Video
		encargs="$encargs -maxrate 3M" # Set max total bitrate
		encargs="$encargs -bufsize 3M" # Set buffer size
		encargs="$encargs -c:v h264" # H.264 video
		encargs="$encargs -pix_fmt yuv420p" # Keep H.264 high profile valid
		encargs="$encargs -vsync vfr" # Allow varible frame rate
		encargs="$encargs -b:v 2856k" # Set video bitrate
		encargs="$encargs -profile:v high" # Use H.264 high profile
		encargs="$encargs -level:v 5.2" # Use level 5.2
		encargs="$encargs -preset slow" # Treat more time for quality
		# Audio
		activate_aac 144
		# Other
		twopass=1
		[ -z "$outfileExt" ] && outfileExt="mp4"
	;;

	"4m")
		# Video
		encargs="$encargs -maxrate 4M" # Set max total bitrate
		encargs="$encargs -bufsize 4M" # Set buffer size
		encargs="$encargs -c:v h264" # H.264 video
		encargs="$encargs -pix_fmt yuv420p" # Keep H.264 high profile valid
		encargs="$encargs -vsync vfr" # Allow varible frame rate
		encargs="$encargs -b:v 3840k" # Set video bitrate
		encargs="$encargs -profile:v high" # Use H.264 high profile
		encargs="$encargs -level:v 5.2" # Use level 5.2
		# Audio
		activate_aac 160
		# Other
		twopass=1
		[ -z "$outfileExt" ] && outfileExt="mp4"
	;;

	"6m")
		# Video
		encargs="$encargs -maxrate 6M" # Set max total bitrate
		encargs="$encargs -bufsize 4M" # Set buffer size
		encargs="$encargs -c:v h264" # H.264 video
		encargs="$encargs -pix_fmt yuv420p" # Keep H.264 high profile valid
		encargs="$encargs -vsync vfr" # Allow varible frame rate
		encargs="$encargs -b:v 5808k" # Set video bitrate
		encargs="$encargs -profile:v high" # Use H.264 high profile
		encargs="$encargs -level:v 5.2" # Use level 5.2
		# Audio
		activate_aac 192
		# Other
		twopass=1
		[ -z "$outfileExt" ] && outfileExt="mp4"
	;;

	"8m")
		# Video
		encargs="$encargs -maxrate 8M" # Set max total bitrate
		encargs="$encargs -bufsize 4M" # Set buffer size
		encargs="$encargs -c:v h264" # H.264 video
		encargs="$encargs -pix_fmt yuv420p" # Keep H.264 high profile valid
		encargs="$encargs -vsync vfr" # Allow varible frame rate
		encargs="$encargs -b:v 7808k" # Set video bitrate
		encargs="$encargs -profile:v high" # Use H.264 high profile
		encargs="$encargs -level:v 5.2" # Use level 5.2
		# Audio
		activate_aac 192
		# Other
		twopass=1
		[ -z "$outfileExt" ] && outfileExt="mp4"
	;;


	"scrcast")
		# Video
		encargs="$encargs -c:v h264" # H.264 video
		encargs="$encargs -pix_fmt yuv420p" # Keep H.264 high profile valid
		encargs="$encargs -fpsmax 10" # Limit FPS to 10 or below
		encargs="$encargs -vsync vfr" # Allow varible frame rate
		encargs="$encargs -crf 36" # Encode all frames with same quality
		encargs="$encargs -profile:v high" # Use H.264 high profile
		encargs="$encargs -level:v 5.2" # Use level 5.2
		encargs="$encargs -tune animation" # Tune for animated large flat areas
		encargs="$encargs -preset veryslow" # Treat more time for quality
		# Audio
		activate_aac 24 mono
		# Other
		[ -z "$outfileExt" ] && outfileExt="mp4"
	;;

	"webcast")
		# Video
		encargs="$encargs -c:v vp9" # VP9 video
		encargs="$encargs -fpsmax 10" # Limit FPS to 10 or below
		encargs="$encargs -vsync vfr" # Allow varible frame rate
		encargs="$encargs -crf 54" # Encode all frames with same quality
		encargs="$encargs -tune-content screen" # Tune for screen recording
		encargs="$encargs -cpu-used 0" # Trade speed for quality
		encargs="$encargs -lag-in-frames 25" # Trade lag for quality
		encargs="$encargs -auto-alt-ref 6" # Trade lag for quality
		encargs="$encargs -row-mt 1" # Use multiple cores more aggressively
		# Audio
        encargs="$encargs -c:a libopus" # Opus audio
        encargs="$encargs -b:a 24k" # Set bitrate
        encargs="$encargs -ar 24000" # Lower sampling rate to 24000 Hz
        encargs="$encargs -ac 1" # Convert audio to mono
		# Other
		[ -z "$outfileExt" ] && outfileExt="webm"
		onexit "rm -f opsnr.stt"
	;;


	"bug")
		# Video
		decargs="$decargs -an" # Don't even decode audio
		encargs="$encargs -c:v h264" # H.264 video
		encargs="$encargs -pix_fmt yuv420p" # Keep H.264 high profile valid
		encargs="$encargs -fpsmax 10" # Limit FPS to 10 or below
		encargs="$encargs -vsync vfr" # Allow varible frame rate
		encargs="$encargs -crf 36" # Encode all frames with same quality
		encargs="$encargs -profile:v high" # Use H.264 high profile
		encargs="$encargs -level:v 5.2" # Use level 5.2
		encargs="$encargs -tune animation" # Tune for animated large flat areas
		encargs="$encargs -preset veryslow" # Treat more time for quality
		[ -z "$outfileExt" ] && outfileExt="mp4"
	;;

	"bugwebm")
		# Video
		decargs="$decargs -an" # Don't even decode audio
		encargs="$encargs -c:v vp9" # VP9 video
		encargs="$encargs -fpsmax 10" # Limit FPS to 10 or below
		encargs="$encargs -vsync vfr" # Allow varible frame rate
		encargs="$encargs -crf 54" # Encode all frames with same quality
		encargs="$encargs -tune-content screen" # Tune for screen recording
		encargs="$encargs -cpu-used 0" # Trade speed for quality
		encargs="$encargs -lag-in-frames 25" # Trade lag for quality
		encargs="$encargs -auto-alt-ref 6" # Trade lag for quality
		encargs="$encargs -row-mt 1" # Use multiple cores more aggressively
		# Other
		[ -z "$outfileExt" ] && outfileExt="webm"
		onexit "rm -f opsnr.stt"
	;;


	"gif")
		# Video
		decargs="$decargs -an" # Don't even decode audio
		encargs="$encargs -fpsmax 10" # Limit FPS to 10 or below
		# Other
		[ -z "$outfileExt" ] && outfileExt="gif"
	;;

	"gifo")
		# Video
		decargs="$decargs -an" # Don't even decode audio
		encargs="$encargs -fpsmax 10" # Limit FPS to 10 or below
		# Other
		[ -z "$outfileExt" ] && outfileExt="gif"
	;;


	"transform")
        if [ -z "$outfileExt" ]
        then
            error "Profile \"transform\" requires \"extension\" option!"
        fi
        if [ -n "$scarg" ]
        then
            error "Profile \"transform\" does not support \"scale\" option!"
        fi
        if [ -n "$volarg" ]
        then
            error "Profile \"transform\" does not support \"volume\" option!"
        fi
		encargs="$encargs -c:v copy" # Copy video data
		encargs="$encargs -c:a copy" # Copy audio data
		;;


	*)
		error "Unknown profile \"$profile\"!"
	;;
esac


abspath()
(
    path=$1

    if [ ! -e "$path" ]; then
        return 1
    fi

    file=
    dir="$path"
    if [ ! -d "$dir" ]; then
        file=$( basename "$dir" )
        dir=$( dirname "$dir" )
    fi

    case "$dir" in
        /*) ;;
        *) dir="$( pwd )/$dir"
    esac
    result=$( cd "$dir" && pwd )

    if [ -n "$file" ]; then
        case "$result" in
            */) ;;
            *) result="$result/"
        esac
        result="$result$file"
    fi

    printf "%s\n" "$result"
)


basenameWithoutExt()
{
    printf '%s' "$( basename "$1" | cut -f1 -d'.' )"
}


calcMaxVolume()
{
    printf "%s\n" "==> Analyzing audio, please wait..."
    volarg=$(
        ffmpeg -i "$1" -filter:a volumedetect \
            -f null /dev/null 2>&1 \
        | grep max_volume \
        | sed 's/.*max_volume: -\{0,1\}\([0-9.]\{1,\}\) dB$/\1/'
    )
    if [ "$volarg" = "0.0" ]
    then
        printf "%s\n" "==> Volume already at maximum."
        volarg=
    else
        printf "%s\n" "==> Emphasizing volume by $volarg dB."
        volarg="volume=${volarg}dB"
    fi
}


while [ $inCount -gt 0 ]
do
    printf "\n%s\n" "====> Next File: $1"

    [ "$volume" = "max" ] && calcMaxVolume "$1"

    if [ -d "$output" ]
    then
        outfile="$output/$( basenameWithoutExt "$1" ).$outfileExt"
        if [ "$(abspath "$1")" = "$(abspath "$outfile")" ]
        then
            echo "Input file cannot override itself!" >&2
            exit 1
        fi
    else
        outfile="$output"
    fi

    case "$profile" in

		"gifo")
			tempdir=$(mktemp -d)
			onexit "rm -r '$tempdir'"

			palette="$tempdir/palette.png"
			p1args="-filter_complex \"[0:v] palettegen\""
			p2args="-i \"$palette\" -filter_complex \"[0:v][1:v] paletteuse\""

			filterargs=
			[ -n "$scarg" ] && filterargs="-filter:v \"$scarg\""

			eval ffmpeg "$decargs" -i "\"$1\"" \
				"$encargs" "$filterargs" "$p1args" "\"$palette"\"

			eval ffmpeg "$decargs" -i "\"$1\"" \
				"$p2args" "$encargs" "$filterargs" "\"$outfile"\"
		;;


        *)
            filterargs=
            [ -n "$volarg" ] && filterargs="-filter:a $volarg"
			[ -n "$scarg" ] && filterargs="$filterargs  -filter:v \"$scarg\""

			if [ -n "$twopass" ]
			then
				tempdir=$(mktemp -d)
				onexit "rm -r '$tempdir'"

				passlog="-passlogfile \"$tempdir/2pass.log\""
				p1args="-pass 1 $passlog -f null"
				p2args="-pass 2 $passlog"

				eval ffmpeg "$decargs" -i "\"$1\"" \
					"$encargs" "$filterargs" "$p1args" /dev/null

				eval ffmpeg "$decargs" -i "\"$1\"" \
					"$encargs" "$filterargs" "$p2args" "\"$outfile"\"
			else
				eval ffmpeg "$decargs" -i "\"$1\"" \
					"$encargs $filterargs" "\"$outfile"\"
			fi
        ;;
    esac
    shift
    inCount=$(( inCount - 1 ))
    printf "\n\n"
done
